title: Copy Of Kate
email: author@copy-of-kate.com
description: Copy Of Kate is an online novel that is currently in progress. All words subject to change.

# Build settings
markdown: kramdown
theme: bookend
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE
  - README.md
port: 1337

sass:
    style: compressed
